<?php

namespace AppBundle\Repository;

/**
 * AddressDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressDataRepository extends \Doctrine\ORM\EntityRepository
{
	public function delete(AddressDataInterface $address) {
		$em = $this->getEntityManager();
		$em->remove($address);
		$em->flush();
	}
	
	public function save(AddressDataInterface $address) {
		$em = $this->getEntityManager();
		$em->persist($address);
		$em->flush();
	}
}
