<?php

namespace AppBundle\Repository;

/**
 * LocationDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationDataRepository extends \Doctrine\ORM\EntityRepository
{
}
