<?php

namespace AppBundle\Repository;
use AppBundle\Model\ParcelInterface;

/**
 * PostmanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostmanRepository extends \Doctrine\ORM\EntityRepository
{
    public function delete(PostmanInterface $postman) {
        $em = $this->getEntityManager();
        $em->remove($postman);
        $em->flush();
    }
    public function save(PostmanInterface $postman) {
        $em = $this->getEntityManager();
        $em->persist($postman);
        $em->flush();
    }
    
    public function edit($request, $postman)
    {
        //$form = $this->buildForm(PostmanType::class, $request);
        $postman->setFirstName($request->request->get('first_name'));
        $postman->setLastName($request->request->get('last_name'));
        $postman->setPhone($request->request->get('phone'));
        $postman->setEmail($request->request->get('email'));
        $postman->setCity($request->request->get('city'));
        return $postman;
    }
}
